version: "3"
services: 
  api:
    container_name: todo-api
    build: .
    ports:
      - 3000:3000
    depends_on: 
      - db
    environment: 
      - MONGODB_URL=mongodb://db:27017/dev
  db:
    container_name: todo-db
    image: mongo
    ports:
      - 27017:27017